### PR TITLE
Fix exposure score card agg

### LINKED ISSUE #196: scorecard/transition: exposure and emissions coverage
emissions and exposure values in score card section on the transition should refer to the sectors covered in the aggregate score, not the total portfolio

### PR DESCRIPTION
**Pull request by jacobvjk**
closes #196

also adds a duplicate of pacta.`portfolio`.analysis `write_log` function to avoid calling an internal function from another package which caused warnings and R CMD fails

### CODE REVIEW

File: R/prep_scores_scorecard.R [hunk 1]
```diff
@@ -47,3 +47,100 @@ prep_scores_scorecard <- function(results_portfolio,
...
+          ) %>%
+          dplyr::group_by(covered_aggregate_score) %>%
+          dplyr::summarise(
+            emissions_pacta = sum(.data$weighted_sector_emissions, na.rm = TRUE),
+            .groups = "drop"
+          ) %>%
+          dplyr::ungroup() %>%
+          dplyr::mutate(
+            emissions_portfolio = sum(.data$emissions_pacta, na.rm = TRUE),
+            emissions_pacta_percent = emissions_pacta / emissions_portfolio
```
Comment (cjyetman) [inline R/prep_scores_scorecard.R:82]:
```suggestion
            emissions_pacta_percent = .data$emissions_pacta / .data$emissions_portfolio
```

File: R/prep_scores_scorecard.R [hunk 2]
```diff
@@ -47,3 +47,100 @@ prep_scores_scorecard <- function(results_portfolio,
...
+          ) %>%
+          dplyr::filter(.data$covered_aggregate_score) %>%
+          dplyr::pull("emissions_pacta_percent")
+
+        stopifnot(length(data_out) == 1)
```
Comment (cjyetman) [inline R/prep_scores_scorecard.R:87]:
```suggestion
        stopifnot(length(data_out) == 1L)
```

File: R/prep_scores_scorecard.R [hunk 3]
```diff
@@ -47,3 +47,100 @@ prep_scores_scorecard <- function(results_portfolio,
...
+
+        return(data_out)
+      },
+      error = function(e) {
+        pacta.portfolio.analysis:::write_log(
+          "ES: There was an error in prep_scores_emissions_scorecard().\nReturning NULL.\n",
+          file_path = log_dir
```
Comment (cjyetman) [inline R/prep_scores_scorecard.R:94]:
```suggestion
          file_path = .GlobalEnv$log_dir
```

does this expect `log_dir` to be in there global environment?

File: R/prep_scores_scorecard.R [hunk 4]
```diff
@@ -47,3 +47,100 @@ prep_scores_scorecard <- function(results_portfolio,
...
+#' @param currency_exchange_value Numeric vector with exchange rate
+#' @param total_portfolio_value_curr Numeric vector with total portfolio value
+#'   in target currency
+#'
+#' @return numeric
+#' @export
+prep_scores_exposure_scorecard <- function(audit_data,
+                                           currency_exchange_value,
+                                           total_portfolio_value_curr) {
+  if (any(is.null(emissions) | is.null(currency_exchange_value) | is.null(total_portfolio_value_curr))) {
```
Comment (cjyetman) [inline R/prep_scores_scorecard.R:114]: Im think `any()` is superfluous here, no? And `||` is usually better in this construction because it evaluates left to right.
```suggestion
  if (is.null(emissions) || is.null(currency_exchange_value) || is.null(total_portfolio_value_curr)) {
```

File: R/prep_scores_scorecard.R [hunk 5]
```diff
@@ -47,3 +47,100 @@ prep_scores_scorecard <- function(results_portfolio,
...
+          dplyr::filter(
+            .data$financial_sector %in% c("Automotive", "Coal", "Oil&Gas", "Power", "Aviation", "Steel")
+          ) %>%
+          dplyr::mutate(value_curr = .data$value_usd / .env$currency_exchange_value) %>%
+          dplyr::pull("value_curr") %>%
+          sum(na.rm = TRUE)
+
+        data_out <- value_covered / total_portfolio_value_curr
+
+        stopifnot(length(data_out) == 1)
```
Comment (cjyetman) [inline R/prep_scores_scorecard.R:133]:
```suggestion
        stopifnot(length(data_out) == 1L)
```

File: R/prep_scores_scorecard.R [hunk 6]
```diff
@@ -47,3 +47,100 @@ prep_scores_scorecard <- function(results_portfolio,
...
+
+        return(data_out)
+      },
+      error = function(e) {
+        pacta.portfolio.analysis:::write_log(
+          "ES: There was an error in prep_scores_exposure_scorecard().\nReturning NULL.\n",
+          file_path = log_dir
```
Comment (cjyetman) [inline R/prep_scores_scorecard.R:140]:
```suggestion
          file_path = .GlobalEnv$log_dir
```

File: inst/extdata/PA2022CH_de_exec_summary/scorecard.Rmd [hunk 7]
```diff
@@ -42,23 +42,23 @@ tryCatch(
 total_portfolio_value_curr <- audit_data %>%
   dplyr::filter(.data$entity == "portfolio") %>%
   dplyr::mutate(value_usd = dplyr::if_else(value_usd < 0, 0, value_usd)) %>%
-  dplyr::mutate(value_curr = value_usd / currency_exchange_value) %>%
-  dplyr::pull(value_curr) %>%
+  dplyr::mutate(value_curr = .data$value_usd / currency_exchange_value) %>%
```
Comment (cjyetman) [inline inst/extdata/PA2022CH_de_exec_summary/scorecard.Rmd:45]:
```suggestion
  dplyr::mutate(value_curr = .data$value_usd / .env$currency_exchange_value) %>%
```

File: inst/extdata/PA2022CH_de_exec_summary/scorecard.Rmd [hunk 8]
```diff
@@ -42,23 +42,23 @@ tryCatch(
...
+  dplyr::pull("value_curr") %>%
   sum(na.rm = TRUE)
 
 total_portfolio_percentage_equity <- (audit_data %>%
   dplyr::filter(.data$entity == "portfolio") %>%
-  filter(asset_type == "Equity") %>%
-  mutate(value_curr = value_usd / currency_exchange_value) %>%
-  dplyr::pull(value_curr) %>%
+  dplyr::filter(.data$asset_type == "Equity") %>%
+  dplyr::mutate(value_curr = .data$value_usd / currency_exchange_value) %>%
```
Comment (cjyetman) [inline inst/extdata/PA2022CH_de_exec_summary/scorecard.Rmd:52]:
```suggestion
  dplyr::mutate(value_curr = .data$value_usd / .env$currency_exchange_value) %>%
```

File: inst/extdata/PA2022CH_de_exec_summary/scorecard.Rmd [hunk 9]
```diff
@@ -42,23 +42,23 @@ tryCatch(
...
   sum(na.rm = TRUE)) /
   total_portfolio_value_curr
 
 total_portfolio_percentage_bonds <- (audit_data %>%
   dplyr::filter(.data$entity == "portfolio") %>%
-  filter(asset_type == "Bonds") %>%
-  mutate(value_curr = value_usd / currency_exchange_value) %>%
-  dplyr::pull(value_curr) %>%
+  dplyr::filter(.data$asset_type == "Bonds") %>%
+  dplyr::mutate(value_curr = .data$value_usd / currency_exchange_value) %>%
```
Comment (cjyetman) [inline inst/extdata/PA2022CH_de_exec_summary/scorecard.Rmd:60]:
```suggestion
  dplyr::mutate(value_curr = .data$value_usd / .env$currency_exchange_value) %>%
```

File: inst/extdata/PA2022CH_en_exec_summary/scorecard.Rmd [hunk 10]
```diff
@@ -42,23 +42,23 @@ tryCatch(
 total_portfolio_value_curr <- audit_data %>%
   dplyr::filter(.data$entity == "portfolio") %>%
   dplyr::mutate(value_usd = dplyr::if_else(value_usd < 0, 0, value_usd)) %>%
-  dplyr::mutate(value_curr = value_usd / currency_exchange_value) %>%
-  dplyr::pull(value_curr) %>%
+  dplyr::mutate(value_curr = .data$value_usd / currency_exchange_value) %>%
```
Comment (cjyetman) [inline inst/extdata/PA2022CH_en_exec_summary/scorecard.Rmd:45]:
```suggestion
  dplyr::mutate(value_curr = .data$value_usd / .env$currency_exchange_value) %>%
```

File: inst/extdata/PA2022CH_en_exec_summary/scorecard.Rmd [hunk 11]
```diff
@@ -42,23 +42,23 @@ tryCatch(
...
+  dplyr::pull("value_curr") %>%
   sum(na.rm = TRUE)
 
 total_portfolio_percentage_equity <- (audit_data %>%
   dplyr::filter(.data$entity == "portfolio") %>%
-  filter(asset_type == "Equity") %>%
-  mutate(value_curr = value_usd / currency_exchange_value) %>%
-  dplyr::pull(value_curr) %>%
+  dplyr::filter(.data$asset_type == "Equity") %>%
+  dplyr::mutate(value_curr = .data$value_usd / currency_exchange_value) %>%
```
Comment (cjyetman) [inline inst/extdata/PA2022CH_en_exec_summary/scorecard.Rmd:52]:
```suggestion
  dplyr::mutate(value_curr = .data$value_usd / .env$currency_exchange_value) %>%
```

File: inst/extdata/PA2022CH_en_exec_summary/scorecard.Rmd [hunk 12]
```diff
@@ -42,23 +42,23 @@ tryCatch(
...
   sum(na.rm = TRUE)) /
   total_portfolio_value_curr
 
 total_portfolio_percentage_bonds <- (audit_data %>%
   dplyr::filter(.data$entity == "portfolio") %>%
-  filter(asset_type == "Bonds") %>%
-  mutate(value_curr = value_usd / currency_exchange_value) %>%
-  dplyr::pull(value_curr) %>%
+  dplyr::filter(.data$asset_type == "Bonds") %>%
+  dplyr::mutate(value_curr = .data$value_usd / currency_exchange_value) %>%
```
Comment (cjyetman) [inline inst/extdata/PA2022CH_en_exec_summary/scorecard.Rmd:60]:
```suggestion
  dplyr::mutate(value_curr = .data$value_usd / .env$currency_exchange_value) %>%
```

File: inst/extdata/PA2022CH_fr_exec_summary/scorecard.Rmd [hunk 13]
```diff
@@ -42,23 +42,23 @@ tryCatch(
 total_portfolio_value_curr <- audit_data %>%
   dplyr::filter(.data$entity == "portfolio") %>%
   dplyr::mutate(value_usd = dplyr::if_else(value_usd < 0, 0, value_usd)) %>%
-  dplyr::mutate(value_curr = value_usd / currency_exchange_value) %>%
-  dplyr::pull(value_curr) %>%
+  dplyr::mutate(value_curr = .data$value_usd / currency_exchange_value) %>%
```
Comment (cjyetman) [inline inst/extdata/PA2022CH_fr_exec_summary/scorecard.Rmd:45]:
```suggestion
  dplyr::mutate(value_curr = .data$value_usd / .env$currency_exchange_value) %>%
```

File: inst/extdata/PA2022CH_fr_exec_summary/scorecard.Rmd [hunk 14]
```diff
@@ -42,23 +42,23 @@ tryCatch(
...
+  dplyr::pull("value_curr") %>%
   sum(na.rm = TRUE)
 
 total_portfolio_percentage_equity <- (audit_data %>%
   dplyr::filter(.data$entity == "portfolio") %>%
-  filter(asset_type == "Equity") %>%
-  mutate(value_curr = value_usd / currency_exchange_value) %>%
-  dplyr::pull(value_curr) %>%
+  dplyr::filter(.data$asset_type == "Equity") %>%
+  dplyr::mutate(value_curr = .data$value_usd / currency_exchange_value) %>%
```
Comment (cjyetman) [inline inst/extdata/PA2022CH_fr_exec_summary/scorecard.Rmd:52]:
```suggestion
  dplyr::mutate(value_curr = .data$value_usd / .env$currency_exchange_value) %>%
```

File: inst/extdata/PA2022CH_fr_exec_summary/scorecard.Rmd [hunk 15]
```diff
@@ -42,23 +42,23 @@ tryCatch(
...
   sum(na.rm = TRUE)) /
   total_portfolio_value_curr
 
 total_portfolio_percentage_bonds <- (audit_data %>%
   dplyr::filter(.data$entity == "portfolio") %>%
-  filter(asset_type == "Bonds") %>%
-  mutate(value_curr = value_usd / currency_exchange_value) %>%
-  dplyr::pull(value_curr) %>%
+  dplyr::filter(.data$asset_type == "Bonds") %>%
+  dplyr::mutate(value_curr = .data$value_usd / currency_exchange_value) %>%
```
Comment (cjyetman) [inline inst/extdata/PA2022CH_fr_exec_summary/scorecard.Rmd:60]:
```suggestion
  dplyr::mutate(value_curr = .data$value_usd / .env$currency_exchange_value) %>%
```

**Comment by jacobvjk** [comment]
@AlexAxthelm this re-export of rasterGrob seems to cause checks to feel
@cjyetman this package is also complaining about undeclared import of write_log from pacta.portfolio.analysis, so I think I will just replicate the function here

**Comment by jdhoffa** [comment]
> @AlexAxthelm this re-export of rasterGrob seems to cause checks to feel @cjyetman this package is also complaining about undeclared import of write_log from pacta.portfolio.analysis, so I think I will just replicate the function here

The re-export of rasterGrob was necessary to get around the fact that it is not a dependency in the traditional sense (it is not required for anything functions in the package), but rather it is required by a .Rmd file that the package calls/ renders. Rather than remove it can you just open a new issue, and I will have a look tomorrow? (and we can accept the note there in CI/CD for now)

**Comment by jdhoffa** [comment]
And regarding write_log, lets think about that a bit more perhaps... since we want both `pacta.portfolio.analysis` functions and `pacta.executive.summary` functions to write to the exact same log, I think it's important that they implement the same function (so that one doesn't fall out of sync with the other)... 

Would potentially rather depending on `pacta.portfolio.analysis` in that case? not sure

**Comment by jacobvjk** [comment]
> And regarding write_log, lets think about that a bit more perhaps... since we want both `pacta.portfolio.analysis` functions and `pacta.executive.summary` functions to write to the exact same log, I think it's important that they implement the same function (so that one doesn't fall out of sync with the other)...
> 
> Would potentially rather depending on `pacta.portfolio.analysis` in that case? not sure

totally fine with that, but since it's not exported right now, I can't seem to add it as a dependency, so the checks will also complain. It still works, presumable because the `pacta.portfolio.analysis` is also installed in the same environment and I am using `:::`
but not v pretty

**Comment by jdhoffa** [comment]
> > And regarding write_log, lets think about that a bit more perhaps... since we want both `pacta.portfolio.analysis` functions and `pacta.executive.summary` functions to write to the exact same log, I think it's important that they implement the same function (so that one doesn't fall out of sync with the other)...
> > Would potentially rather depending on `pacta.portfolio.analysis` in that case? not sure
> 
> totally fine with that, but since it's not exported right now, I can't seem to add it as a dependency, so the checks will also complain. It still works, presumable because the `pacta.portfolio.analysis` is also installed in the same environment and I am using `:::` but not v pretty

ah crap yes understood ok. Ok then totally just re-write it. Not worth the hassle

**Comment by jacobvjk** [comment]
> > @AlexAxthelm this re-export of rasterGrob seems to cause checks to feel @cjyetman this package is also complaining about undeclared import of write_log from pacta.portfolio.analysis, so I think I will just replicate the function here
> 
> The re-export of rasterGrob was necessary to get around the fact that it is not a dependency in the traditional sense (it is not required for anything functions in the package), but rather it is required by a .Rmd file that the package calls/ renders. Rather than remove it can you just open a new issue, and I will have a look tomorrow? (and we can accept the note there in CI/CD for now)

doesn't seem to cause fails anymore, maybe the internal function was the actual issue...

File: R/prep_scores_scorecard.R (hunk 6 above)
Comment (jacobvjk) [reply R/prep_scores_scorecard.R:146]: added new arg instead

Comment (jdhoffa) [reply R/prep_scores_scorecard.R:146]: If you add a new arg, you need to make sure that that arg is passed now every time the function is called!
I think easiest might be to add the arg with a default value of `.GlobalEnv$log_dir`.

File: R/prep_scores_scorecard.R [hunk 16]
```diff
@@ -47,3 +47,106 @@ prep_scores_scorecard <- function(results_portfolio,
...
+
+#' Prepare share of portfolio emissions covered by aggregate score analysis
+#'
+#' @param emissions_data Data frame that contains pre-wrangled emissions data
+#' @param log_dir Path to log file
+#'
+#' @return numeric
+#' @export
+prep_scores_emissions_scorecard <- function(emissions_data,
+                                            log_dir) {
```
Comment (jdhoffa) [inline R/prep_scores_scorecard.R:59]: If you add an arg `log_dir` here, you will need to add that argument to every place it is called (e.g. in the `.Rmd` template). 

I think the safest approach would be to add the arg, with a default value of `GlobalEnv$log_dir`:

``` r
prep_scores_emissions_scorecard <- function(emissions_data, log_dir = GlobalEnv$log_dir) {
```

Comment (jacobvjk) [reply R/prep_scores_scorecard.R:59]: I did add it everywhere it is used, but happy to add the default. would it not be `.GlobalEnv$log_dir` however?

Comment (jacobvjk) [reply R/prep_scores_scorecard.R]: done

**Review by jdhoffa — APPROVED** [review]
lgtm
